version: "3.6"
services:
  postgres:
    image: postgres:10.3
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  graphql-engine:
    image: hasura/graphql-engine
    depends_on:
      - "postgres"
    command:
      - graphql-engine
      - serve
    env_file:
      - .env

  caddy:
    image: abiosoft/caddy:0.11.0
    depends_on:
      - "graphql-engine"
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/Caddyfile
      - caddy_certs:/root/.caddy

  # pgadmin:
  #   image: page/pgadmin4
  #   ports:
  #     - "8888:8888"
  #   env_file:
  #     - .env

volumes:
  pgdata: ~
  caddy_certs: ~
